"""Backend-independent repository ports for input runtime."""
from __future__ import annotations
from datetime import datetime
from typing import Protocol, runtime_checkable
from .models import *

@runtime_checkable
class SessionInputRuntimeRepository(Protocol):
    async def get_state(self,session_id:str)->SessionInputRuntimeState|None: ...
    async def create_state_if_absent(self,state:SessionInputRuntimeState)->SessionInputRuntimeState: ...
    async def compare_and_swap_state(self,state:SessionInputRuntimeState,*,expected_revision:int)->SessionInputRuntimeState:
        """Replace only the expected revision and return the new revision; conflict raises a managed conflict error."""
        ...
    async def list_recoverable_states(self)->list[SessionInputRuntimeState]: ...
@runtime_checkable
class InputAdmissionRepository(Protocol):
    async def get_admission(self,admission_id:str)->InputAdmissionRecord: ...
    async def find_by_input_batch_id(self,input_batch_id:str)->InputAdmissionRecord|None: ...
    async def create_if_absent(self,record:InputAdmissionRecord)->InputAdmissionRecord: ...
    async def list_session_admissions(self,session_id:str,*,after_session_sequence:int=0,limit:int|None=None)->list[InputAdmissionRecord]: ...
    async def list_cycle_admissions(self,cycle_id:str,*,after_cycle_sequence:int=-1,limit:int|None=None)->list[InputAdmissionRecord]: ...
    async def mark_applied(self,admission_id:str,*,applied_at:datetime)->InputAdmissionRecord: ...
    async def cancel_generation(self,session_id:str,*,generation:int,reason_code:str,cancelled_at:datetime)->list[InputAdmissionRecord]: ...
@runtime_checkable
class CycleInboxRepository(Protocol):
    async def get_item(self,inbox_item_id:str)->CycleInboxItem: ...
    async def enqueue_if_absent(self,item:CycleInboxItem)->CycleInboxItem: ...
    async def list_cycle_items(self,cycle_id:str,*,after_sequence:int=0,states:set[CycleInboxState]|None=None)->list[CycleInboxItem]: ...
    async def claim_next(self,cycle_id:str,*,generation:int,after_sequence:int,max_items:int,max_total_bytes:int,lease_seconds:float,now:datetime)->ClaimedInboxRange|None: ...
    async def mark_applying(self,claim:ClaimedInboxRange,*,now:datetime)->ClaimedInboxRange: ...
    async def mark_applied(self,claim:ClaimedInboxRange,*,applied_at:datetime)->list[CycleInboxItem]: ...
    async def requeue_claim(self,claim_token:str,*,reason_code:str,now:datetime)->list[CycleInboxItem]: ...
    async def list_expired_claims(self,*,now:datetime)->list[ClaimedInboxRange]: ...
    async def cancel_generation(self,session_id:str,*,generation:int,reason_code:str,cancelled_at:datetime)->list[CycleInboxItem]: ...
@runtime_checkable
class SessionControlRepository(Protocol):
    async def get_control(self,control_id:str)->SessionControlCommand: ...
    async def append_if_absent(self,command:SessionControlCommand)->SessionControlCommand: ...
    async def list_pending_controls(self,session_id:str,*,generation:int,after_sequence:int=0)->list[SessionControlCommand]: ...
    async def acknowledge(self,control_id:str,*,acknowledged_at:datetime)->SessionControlCommand: ...
    async def mark_applied(self,control_id:str,*,applied_at:datetime)->SessionControlCommand: ...
    async def reject(self,control_id:str,*,rejection_code:str,rejected_at:datetime)->SessionControlCommand: ...
    async def cancel_generation(self,session_id:str,*,generation:int,reason_code:str,cancelled_at:datetime)->list[SessionControlCommand]: ...
@runtime_checkable
class ActiveCycleSnapshotRepository(Protocol):
    async def get_snapshot(self,cycle_id:str)->ActiveCycleSnapshot|None: ...
    async def create_initial_snapshot(self,snapshot:ActiveCycleSnapshot)->ActiveCycleSnapshot: ...
    async def compare_and_swap_snapshot(self,snapshot:ActiveCycleSnapshot,*,expected_revision:int)->ActiveCycleSnapshot: ...
    async def list_recoverable_snapshots(self)->list[ActiveCycleSnapshot]: ...
@runtime_checkable
class ContextRevisionRepository(Protocol):
    async def get_revision(self,context_revision_id:str)->CycleContextRevision: ...
    async def append_revision(self,revision:CycleContextRevision)->CycleContextRevision: ...
    async def list_cycle_revisions(self,cycle_id:str)->list[CycleContextRevision]: ...
    async def get_latest_revision(self,cycle_id:str)->CycleContextRevision|None: ...
@runtime_checkable
class AgentEmissionRepository(Protocol):
    async def get_emission(self,emission_id:str)->AgentEmission: ...
    async def create_if_absent(self,emission:AgentEmission)->AgentEmission: ...
    async def claim_ready(self,*,limit:int,lease_seconds:float,now:datetime)->AgentEmissionClaim|None: ...
    async def mark_delivered(self,emission_id:str,*,delivered_at:datetime)->AgentEmission: ...
    async def mark_failed(self,emission_id:str,*,error_code:str,retryable:bool)->AgentEmission: ...
    async def mark_unknown(self,emission_id:str,*,error_code:str)->AgentEmission: ...
    async def list_recoverable(self)->list[AgentEmission]: ...
@runtime_checkable
class FinalizationRepository(Protocol):
    async def get_finalization(self,finalization_id:str)->CycleFinalizationRecord: ...
    async def find_active_for_cycle(self,cycle_id:str)->CycleFinalizationRecord|None: ...
    async def prepare_if_absent(self,record:CycleFinalizationRecord)->CycleFinalizationRecord: ...
    async def advance_state(self,finalization_id:str,*,expected_state:FinalizationState,next_record:CycleFinalizationRecord)->CycleFinalizationRecord: ...
    async def list_recoverable(self)->list[CycleFinalizationRecord]: ...
