"""Public API for the v0.4 artifact foundation."""

from .candidate_store import (
    ArtifactCandidateStore,
    FileSystemArtifactCandidateStore,
)
from .config import ArtifactConfigType, load_artifact_config
from .delivery import (
    ArtifactDeliveryRecord,
    ArtifactDeliveryService,
    FileSystemArtifactDeliveryStore,
)
from .delivery_recovery import recover_stale_delivery_claims
from .errors import (
    ArtifactAccessError,
    ArtifactCandidateError,
    ArtifactCapabilityError,
    ArtifactConfigValidationError,
    ArtifactDeliveryError,
    ArtifactDeliveryNotFoundError,
    ArtifactError,
    ArtifactFilenameConflictError,
    ArtifactIntegrityError,
    ArtifactLimitError,
    ArtifactNotFoundError,
    ArtifactStorageError,
    ArtifactValidationError,
    ArtifactVersionConflictError,
    ArtifactWorkspaceError,
)
from .factory import ArtifactServices, create_artifact_services
from .file_store import FileSystemArtifactStore
from .format_registry import (
    ArtifactFormatDetection,
    ArtifactFormatRegistry,
    build_default_format_registry,
)
from .interfaces import ArtifactStore
from .migration import LegacyArtifactMigrator, LegacyMigrationReport
from .models import (
    ArtifactAccessContext,
    ArtifactBatchItemStatus,
    ArtifactBatchReadResult,
    ArtifactBatchSearchResult,
    ArtifactBatchStatus,
    ArtifactCandidate,
    ArtifactCandidateStatus,
    ArtifactCapability,
    ArtifactCatalogCapabilities,
    ArtifactCatalogItem,
    ArtifactCatalogResult,
    ArtifactContentKind,
    ArtifactDeliveryRef,
    ArtifactDeliveryBatchItem,
    ArtifactDeliveryBatchResult,
    ArtifactDeliveryState,
    ArtifactFormatSpec,
    ArtifactFilenameResolution,
    ArtifactFilenameResolutionStatus,
    ArtifactLineage,
    ArtifactLineageStatus,
    ArtifactProvenance,
    ArtifactPurpose,
    ArtifactReadItem,
    ArtifactResultRepresentation,
    ArtifactSearchItem,
    ArtifactVersion,
    ArtifactVersionRef,
    ExactTextPatchOperation,
    is_artifact_candidate_id,
    is_artifact_delivery_id,
    is_artifact_id,
    is_artifact_lineage_id,
    new_artifact_candidate_id,
    new_artifact_delivery_id,
    new_artifact_id,
    new_artifact_lineage_id,
    normalize_artifact_filename,
    utc_now,
)
from .progress import register_artifact_progress_messages
from .promotion import ArtifactCandidatePromotionService
from .server_policy import apply_local_workspace_server_policy
from .service import ArtifactSearchResult, ArtifactService, ArtifactTextReadResult
from .text_operations import apply_exact_text_patch, enforce_text_size
from .tracing import (
    ArtifactTraceArtifact,
    ArtifactTraceCorrelation,
    ArtifactTraceError,
    ArtifactTraceEvent,
    ArtifactTraceService,
    ArtifactTraceStore,
    ArtifactTraceTransport,
    FileSystemArtifactTraceStore,
    new_artifact_trace_event_id,
)
from .validators import ArtifactValidationReport, validate_native_text
from .workspace import (
    ArtifactInputBinding,
    ArtifactOutputSpec,
    ArtifactWorkspace,
    ArtifactWorkspaceManager,
)
from .workspace_recovery import cleanup_stale_artifact_workspaces

__all__ = [
    "ArtifactAccessContext",
    "ArtifactAccessError",
    "ArtifactBatchItemStatus",
    "ArtifactBatchReadResult",
    "ArtifactBatchSearchResult",
    "ArtifactBatchStatus",
    "ArtifactCandidate",
    "ArtifactCandidateError",
    "ArtifactCandidatePromotionService",
    "ArtifactCandidateStatus",
    "ArtifactCandidateStore",
    "ArtifactCapability",
    "ArtifactCapabilityError",
    "ArtifactCatalogCapabilities",
    "ArtifactCatalogItem",
    "ArtifactCatalogResult",
    "ArtifactConfigType",
    "ArtifactConfigValidationError",
    "ArtifactContentKind",
    "ArtifactDeliveryError",
    "ArtifactDeliveryBatchItem",
    "ArtifactDeliveryBatchResult",
    "ArtifactDeliveryNotFoundError",
    "ArtifactDeliveryRecord",
    "ArtifactDeliveryRef",
    "ArtifactDeliveryService",
    "ArtifactDeliveryState",
    "ArtifactError",
    "ArtifactFilenameConflictError",
    "ArtifactFilenameResolution",
    "ArtifactFilenameResolutionStatus",
    "ArtifactFormatDetection",
    "ArtifactFormatRegistry",
    "ArtifactFormatSpec",
    "ArtifactInputBinding",
    "ArtifactIntegrityError",
    "ArtifactLimitError",
    "ArtifactLineage",
    "ArtifactLineageStatus",
    "ArtifactNotFoundError",
    "ArtifactOutputSpec",
    "ArtifactProvenance",
    "ArtifactPurpose",
    "ArtifactReadItem",
    "ArtifactResultRepresentation",
    "ArtifactSearchResult",
    "ArtifactService",
    "ArtifactSearchItem",
    "ArtifactServices",
    "ArtifactStorageError",
    "ArtifactStore",
    "ArtifactTextReadResult",
    "ArtifactTraceArtifact",
    "ArtifactTraceCorrelation",
    "ArtifactTraceError",
    "ArtifactTraceEvent",
    "ArtifactTraceService",
    "ArtifactTraceStore",
    "ArtifactTraceTransport",
    "ArtifactValidationError",
    "ArtifactValidationReport",
    "ArtifactVersion",
    "ArtifactVersionConflictError",
    "ArtifactVersionRef",
    "ArtifactWorkspace",
    "ArtifactWorkspaceError",
    "ArtifactWorkspaceManager",
    "ExactTextPatchOperation",
    "FileSystemArtifactCandidateStore",
    "FileSystemArtifactDeliveryStore",
    "FileSystemArtifactStore",
    "FileSystemArtifactTraceStore",
    "LegacyArtifactMigrator",
    "LegacyMigrationReport",
    "apply_exact_text_patch",
    "apply_local_workspace_server_policy",
    "build_default_format_registry",
    "cleanup_stale_artifact_workspaces",
    "create_artifact_services",
    "enforce_text_size",
    "is_artifact_candidate_id",
    "is_artifact_delivery_id",
    "is_artifact_id",
    "is_artifact_lineage_id",
    "load_artifact_config",
    "new_artifact_candidate_id",
    "new_artifact_delivery_id",
    "new_artifact_id",
    "new_artifact_lineage_id",
    "new_artifact_trace_event_id",
    "normalize_artifact_filename",
    "recover_stale_delivery_claims",
    "register_artifact_progress_messages",
    "utc_now",
    "validate_native_text",
]
