"""Public API for the v0.4 artifact foundation."""

from .config import ArtifactConfigType, load_artifact_config
from .errors import (
    ArtifactAccessError,
    ArtifactCandidateError,
    ArtifactCapabilityError,
    ArtifactConfigValidationError,
    ArtifactError,
    ArtifactIntegrityError,
    ArtifactLimitError,
    ArtifactNotFoundError,
    ArtifactStorageError,
    ArtifactValidationError,
    ArtifactVersionConflictError,
)
from .factory import ArtifactServices, create_artifact_services
from .file_store import FileSystemArtifactStore
from .format_registry import (
    ArtifactFormatDetection,
    ArtifactFormatRegistry,
    build_default_format_registry,
)
from .interfaces import ArtifactStore
from .migration import LegacyArtifactMigrator, LegacyMigrationReport
from .models import (
    ArtifactAccessContext,
    ArtifactCandidate,
    ArtifactCandidateStatus,
    ArtifactCapability,
    ArtifactContentKind,
    ArtifactDeliveryRef,
    ArtifactDeliveryState,
    ArtifactFormatSpec,
    ArtifactLineage,
    ArtifactLineageStatus,
    ArtifactProvenance,
    ArtifactPurpose,
    ArtifactVersion,
    ArtifactVersionRef,
    ExactTextPatchOperation,
    is_artifact_candidate_id,
    is_artifact_delivery_id,
    is_artifact_id,
    is_artifact_lineage_id,
    new_artifact_candidate_id,
    new_artifact_delivery_id,
    new_artifact_id,
    new_artifact_lineage_id,
    utc_now,
)
from .service import ArtifactSearchResult, ArtifactService, ArtifactTextReadResult
from .text_operations import apply_exact_text_patch, enforce_text_size
from .validators import ArtifactValidationReport, validate_native_text

__all__ = [
    "ArtifactAccessContext",
    "ArtifactAccessError",
    "ArtifactCandidate",
    "ArtifactCandidateError",
    "ArtifactCandidateStatus",
    "ArtifactCapability",
    "ArtifactCapabilityError",
    "ArtifactConfigType",
    "ArtifactConfigValidationError",
    "ArtifactContentKind",
    "ArtifactDeliveryRef",
    "ArtifactDeliveryState",
    "ArtifactError",
    "ArtifactFormatDetection",
    "ArtifactFormatRegistry",
    "ArtifactFormatSpec",
    "ArtifactIntegrityError",
    "ArtifactLimitError",
    "ArtifactLineage",
    "ArtifactLineageStatus",
    "ArtifactNotFoundError",
    "ArtifactProvenance",
    "ArtifactPurpose",
    "ArtifactSearchResult",
    "ArtifactService",
    "ArtifactServices",
    "ArtifactStorageError",
    "ArtifactStore",
    "ArtifactTextReadResult",
    "ArtifactValidationError",
    "ArtifactValidationReport",
    "ArtifactVersion",
    "ArtifactVersionConflictError",
    "ArtifactVersionRef",
    "ExactTextPatchOperation",
    "FileSystemArtifactStore",
    "LegacyArtifactMigrator",
    "LegacyMigrationReport",
    "apply_exact_text_patch",
    "build_default_format_registry",
    "create_artifact_services",
    "enforce_text_size",
    "is_artifact_candidate_id",
    "is_artifact_delivery_id",
    "is_artifact_id",
    "is_artifact_lineage_id",
    "load_artifact_config",
    "new_artifact_candidate_id",
    "new_artifact_delivery_id",
    "new_artifact_id",
    "new_artifact_lineage_id",
    "utc_now",
    "validate_native_text",
]
