"""Real HTTP smoke test for Web artifact ingress, idempotency and delivery.

The default mode does not call the LLM: it uploads two files atomically and
replays the same idempotency key.  ``--run`` additionally executes the committed
batch through the real agent.  ``--expect-delivery`` downloads every selected
deliverable through the instance-scoped OutputBatch outbox, verifies size and
SHA-256, saves it locally and posts one terminal aggregate receipt.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import mimetypes
import os
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx


WEB_CLIENT_INSTANCE_ID = "web-artifact-smoke"

DEFAULT_PROMPT = (
    "Прочитай оба приложенных файла. Сверь данные и ответь кратко: "
    "название проекта, ответственный, приоритет и количество задач. "
    "Не создавай новый файл."
)

DELIVERY_PROMPT = (
    "Прочитай оба приложенных файла. Создай новый Markdown-файл "
    "smoke-result.md с краткой сводкой: название проекта, ответственный, "
    "приоритет, количество задач и список задач. Обязательно выбери готовый "
    "файл для доставки пользователю через artifact_set_delivery."
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Smoke-test Web artifact ingress and delivery endpoints."
    )
    parser.add_argument(
        "--base-url",
        default=os.getenv("GATEWAY_URL", "http://127.0.0.1:8000"),
        help="Gateway base URL (default: GATEWAY_URL or http://127.0.0.1:8000).",
    )
    parser.add_argument(
        "--api-key",
        default=os.getenv("WEB_API_KEY", ""),
        help="Gateway WEB_API_KEY (default: environment variable).",
    )
    parser.add_argument(
        "--conversation-id",
        default=None,
        help="Web conversation ID. A unique value is generated by default.",
    )
    parser.add_argument(
        "--prompt",
        default=None,
        help="Override the instruction sent with the files.",
    )
    parser.add_argument(
        "--run",
        action="store_true",
        help="Run the committed batch through the real agent.",
    )
    parser.add_argument(
        "--expect-delivery",
        action="store_true",
        help="Require delivery refs, download them and post complete receipts.",
    )
    parser.add_argument(
        "--output-dir",
        default="smoke-output",
        help="Directory for downloaded deliverables.",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=1800.0,
        help="HTTP read timeout for a real agent run.",
    )
    return parser.parse_args()


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def response_json(response: httpx.Response, *, expected: set[int]) -> dict[str, Any]:
    if response.status_code not in expected:
        raise RuntimeError(
            f"HTTP {response.status_code} for {response.request.method} "
            f"{response.request.url}: {response.text[:2000]}"
        )
    try:
        payload = response.json()
    except ValueError as error:
        raise RuntimeError(
            f"Expected JSON from {response.request.url}, got: "
            f"{response.text[:2000]}"
        ) from error
    require(isinstance(payload, dict), "Response JSON must be an object")
    return payload


def sample_files() -> list[tuple[str, bytes, str]]:
    markdown = (
        "# Проект Aurora\n\n"
        "Ответственный: Фёдор\n\n"
        "Приоритет: высокий\n\n"
        "## Задачи\n"
        "- Проверить файловый ingress\n"
        "- Проверить идемпотентность\n"
        "- Проверить обратную доставку\n"
    ).encode("utf-8")
    structured = json.dumps(
        {
            "project": "Aurora",
            "owner": "Фёдор",
            "priority": "high",
            "tasks": [
                "Проверить файловый ingress",
                "Проверить идемпотентность",
                "Проверить обратную доставку",
            ],
        },
        ensure_ascii=False,
        indent=2,
    ).encode("utf-8")
    return [
        ("aurora.md", markdown, "text/markdown"),
        ("aurora.json", structured, "application/json"),
    ]


def build_manifest(
    *,
    conversation_id: str,
    idempotency_key: str,
    prompt: str,
    samples: list[tuple[str, bytes, str]],
) -> tuple[dict[str, Any], dict[str, tuple[str, bytes, str]]]:
    slots: list[dict[str, Any]] = []
    multipart_files: dict[str, tuple[str, bytes, str]] = {}
    slot_ids: list[str] = []

    for index, (filename, payload, mime_type) in enumerate(samples, start=1):
        slot_id = f"slot_file_{index}"
        field_name = f"file_{index}"
        slot_ids.append(slot_id)
        slots.append({
            "slot_id": slot_id,
            "media_kind": "document",
            "original_filename": filename,
            "declared_mime_type": mime_type,
            "declared_size_bytes": len(payload),
            "upload_field_name": field_name,
            "metadata": {"smoke_test": True},
        })
        multipart_files[field_name] = (filename, payload, mime_type)

    source_message_id = uuid.uuid4().hex
    manifest = {
        "idempotency_key": idempotency_key,
        "client_type": "web",
        "client_instance_id": WEB_CLIENT_INSTANCE_ID,
        "conversation": {
            "conversation_id": conversation_id,
            "thread_id": None,
        },
        "sender": {
            "principal_id": "smoke-user",
            "display_name": "Artifact Smoke Test",
        },
        "source_update_id": source_message_id,
        "source_message_id": source_message_id,
        "source_group_id": None,
        "reply_to_message_id": None,
        "occurred_at": datetime.now(timezone.utc).isoformat(),
        "text_parts": [{
            "part_id": "instruction",
            "kind": "message_text",
            "text": prompt,
            "attachment_slot_ids": slot_ids,
        }],
        "attachment_slots": slots,
        "locale": "ru",
        "admission_mode": "new_cycle",
        "response_route": {
            "route_type": "web",
            "conversation_id": conversation_id,
            "thread_id": None,
            "reply_to_message_id": None,
            "metadata": {"smoke_test": True},
        },
        "metadata": {"smoke_test": True},
    }
    return manifest, multipart_files


def multipart_payload(
    manifest: dict[str, Any],
    files: dict[str, tuple[str, bytes, str]],
) -> dict[str, tuple[str | None, str | bytes, str]]:
    result: dict[str, tuple[str | None, str | bytes, str]] = {
        "manifest": (
            None,
            json.dumps(manifest, ensure_ascii=False),
            "application/json",
        )
    }
    result.update(files)
    return result


def deliver_output_batch(
    client: httpx.Client,
    *,
    output_batch: dict[str, Any],
    session_id: str,
    output_dir: Path,
) -> list[Path]:
    output_batch_id = str(output_batch.get("output_batch_id") or "")
    require(output_batch_id.startswith("obat_"), "Invalid output_batch_id")
    authority = {
        "session_id": session_id,
        "client_type": "web",
        "client_instance_id": WEB_CLIENT_INSTANCE_ID,
    }
    ready = response_json(
        client.get(
            "/internal/output-outbox/ready",
            params={
                "client_type": "web",
                "client_instance_id": WEB_CLIENT_INSTANCE_ID,
                "minimum_age_seconds": 0,
            },
        ),
        expected={200},
    )
    ready_ids = {
        item.get("output_batch_id")
        for item in ready.get("output_batches", [])
        if isinstance(item, dict)
    }
    require(output_batch_id in ready_ids, "OutputBatch is not READY in Web outbox")

    claim_request_id = "oclm_" + uuid.uuid4().hex
    claim_body = {**authority, "claim_request_id": claim_request_id}
    claimed = response_json(
        client.post(
            f"/internal/output-outbox/{output_batch_id}/claim",
            json=claim_body,
        ),
        expected={200},
    )
    replayed_claim = response_json(
        client.post(
            f"/internal/output-outbox/{output_batch_id}/claim",
            json=claim_body,
        ),
        expected={200},
    )
    attempt_id = str(claimed.get("attempt_id") or "")
    require(attempt_id, "Claim did not return attempt_id")
    require(
        replayed_claim.get("attempt_id") == attempt_id,
        "Exact claim replay returned another attempt",
    )
    claimed_batch = claimed.get("output_batch") or {}
    require(claimed_batch.get("state") == "delivering", "Claim did not start delivery")

    output_dir.mkdir(parents=True, exist_ok=True)
    saved: list[Path] = []
    part_receipts: list[dict[str, Any]] = []
    started_at = datetime.now(timezone.utc).isoformat()
    for part in claimed_batch.get("parts", []):
        require(isinstance(part, dict), "OutputBatch part must be an object")
        receipt: dict[str, Any] = {
            "part_id": part["part_id"],
            "index": part["index"],
            "required": part["required"],
            "state": "delivered",
            "client_message_ids": [
                f"web-smoke:{output_batch_id}:{part['part_id']}"
            ],
            "delivered_at": datetime.now(timezone.utc).isoformat(),
        }
        delivery_id = part.get("delivery_id")
        if delivery_id is not None:
            content_response = client.get(
                f"/internal/output-outbox/{output_batch_id}/deliveries/"
                f"{delivery_id}/content",
                params=authority,
            )
            if content_response.status_code != 200:
                raise RuntimeError(
                    f"Could not download {delivery_id}: HTTP "
                    f"{content_response.status_code}: {content_response.text[:1000]}"
                )
            payload = content_response.content
            expected_size = int(part["size_bytes"])
            expected_hash = content_response.headers.get("X-Content-Hash", "")
            actual_hash = "sha256:" + hashlib.sha256(payload).hexdigest()
            require(len(payload) == expected_size, f"Size mismatch for {delivery_id}")
            require(actual_hash == expected_hash, f"Hash mismatch for {delivery_id}")
            filename = str(part.get("filename") or f"{delivery_id}.bin")
            safe_name = Path(filename).name or f"{delivery_id}.bin"
            target = output_dir / safe_name
            target.write_bytes(payload)
            saved.append(target)
            receipt.update({
                "delivery_id": delivery_id,
                "artifact_content_state": "delivered",
            })
        part_receipts.append(receipt)

    receipt = {
        "output_batch_id": output_batch_id,
        "attempt_id": attempt_id,
        "state": "delivered",
        "part_receipts": part_receipts,
        "started_at": started_at,
        "completed_at": datetime.now(timezone.utc).isoformat(),
    }
    receipt_body = {**authority, "receipt": receipt}
    completed = response_json(
        client.post(
            f"/internal/output-outbox/{output_batch_id}/receipt",
            json=receipt_body,
        ),
        expected={200},
    )
    require(completed.get("state") == "delivered", "OutputBatch did not finish")
    replayed = response_json(
        client.post(
            f"/internal/output-outbox/{output_batch_id}/receipt",
            json=receipt_body,
        ),
        expected={200},
    )
    require(replayed == completed, "Exact receipt replay was not idempotent")
    recovered = response_json(
        client.get(
            f"/internal/output-outbox/{output_batch_id}",
            params=authority,
        ),
        expected={200},
    )
    require(
        (recovered.get("output_batch") or {}).get("state") == "delivered",
        "Terminal OutputBatch could not be recovered by ID",
    )
    return saved


def main() -> int:
    args = parse_args()
    if not args.api_key:
        print("WEB_API_KEY is required (--api-key or environment variable).", file=sys.stderr)
        return 2
    if args.expect_delivery and not args.run:
        print("--expect-delivery requires --run.", file=sys.stderr)
        return 2

    conversation_id = args.conversation_id or f"smoke-{uuid.uuid4().hex}"
    idempotency_key = f"web-smoke:{uuid.uuid4().hex}"
    prompt = args.prompt or (
        DELIVERY_PROMPT if args.expect_delivery else DEFAULT_PROMPT
    )
    samples = sample_files()
    manifest, upload_files = build_manifest(
        conversation_id=conversation_id,
        idempotency_key=idempotency_key,
        prompt=prompt,
        samples=samples,
    )
    headers = {"X-API-Key": args.api_key}
    timeout = httpx.Timeout(
        connect=10.0,
        read=args.timeout,
        write=60.0,
        pool=10.0,
    )

    try:
        with httpx.Client(
            base_url=args.base_url.rstrip("/"),
            headers=headers,
            timeout=timeout,
        ) as client:
            health = response_json(client.get("/health"), expected={200})
            print("[OK] Gateway health:", json.dumps(health, ensure_ascii=False))

            first = response_json(
                client.post(
                    "/web/input-batches",
                    params={"run": "false", "progress_locale": "ru"},
                    files=multipart_payload(manifest, upload_files),
                ),
                expected={201},
            )
            require(first.get("status") == "committed", "First batch was not committed")
            require(first.get("duplicate") is False, "First submission is unexpectedly duplicate")
            committed = first.get("committed_batch") or {}
            batch_id = str(first.get("input_batch_id") or "")
            session_id = str(committed.get("session_id") or "")
            require(batch_id.startswith("ibat_"), "Invalid input_batch_id")
            require(session_id == f"web:conversation:{conversation_id}", "Unexpected session_id")
            require(committed.get("artifact_count") == len(samples), "Unexpected artifact count")
            print(f"[OK] Atomic upload committed: {batch_id} ({session_id})")

            duplicate = response_json(
                client.post(
                    "/web/input-batches",
                    params={"run": "false", "progress_locale": "ru"},
                    files=multipart_payload(manifest, upload_files),
                ),
                expected={200},
            )
            require(duplicate.get("duplicate") is True, "Replay was not detected as duplicate")
            require(duplicate.get("input_batch_id") == batch_id, "Replay returned another batch")
            print("[OK] Idempotent replay returned the original committed batch")

            if not args.run:
                print("[DONE] Ingress/idempotency smoke test passed. LLM was not called.")
                return 0

            run_payload = response_json(
                client.post(
                    f"/input-batches/{batch_id}/run",
                    json={"session_id": session_id, "progress_locale": "ru"},
                ),
                expected={200},
            )
            require(run_payload.get("status") == "ok", "Agent run did not return status=ok")
            print("[OK] Agent response:")
            print(str(run_payload.get("response") or ""))
            metadata = run_payload.get("metadata") or {}
            require(isinstance(metadata, dict), "Agent metadata must be an object")

            deliveries = metadata.get("artifacts") or []
            require(isinstance(deliveries, list), "metadata.artifacts must be a list")
            if args.expect_delivery:
                require(deliveries, "Agent did not select any artifact for delivery")
                output_dir = Path(args.output_dir)
                output_batch = metadata.get("output_batch") or {}
                require(isinstance(output_batch, dict), "Missing OutputBatch metadata")
                targets = deliver_output_batch(
                    client,
                    output_batch=output_batch,
                    session_id=session_id,
                    output_dir=output_dir,
                )
                require(targets, "OutputBatch contained no downloadable artifacts")
                for target in targets:
                    print(f"[OK] Outbox delivery verified: {target}")
            else:
                print(f"[INFO] Selected deliveries: {len(deliveries)}")

            print("[DONE] Full Web artifact workflow smoke test passed.")
            return 0
    except (httpx.HTTPError, RuntimeError, KeyError, ValueError) as error:
        print(f"[FAIL] {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
